name: Extract ZIP and Cleanup

on:
  workflow_dispatch:

jobs:
  extract-and-cleanup:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Extract red1dark-store (2).zip
        run: |
          unzip -o "red1dark-store (2).zip" -d ./
      
      - name: Delete unnecessary files
        run: |
          rm -f LICENSE README.md "logo 1024x1024.png" "logo 915x819.png" templates.zip
      
      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -m "Extract red1dark-store (2).zip and cleanup files"
          git push
